apiVersion: v1
kind: Service
metadata:
  name: assignment-service
  namespace: fixguard
  labels:
    app.kubernetes.io/name: assignment-service
    app.kubernetes.io/part-of: fixguard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: assignment-service
  ports:
    - name: http
      port: 4004
      targetPort: http
      protocol: TCP
