apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: fixguard
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: fixguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
