import cors from "cors";
import express from "express";
import helmet from "helmet";
import { errorHandler, notFoundHandler } from "./middleware/error.middleware.js";
import adminRoutes from "./routes/admin.routes.js";
import locationRoutes from "./routes/location.routes.js";
import internalRoutes from "./routes/internal.routes.js";
import { installMetrics } from "./metrics.js";
const app = express(); app.use(helmet()); app.use(cors({ origin: process.env.FRONTEND_URL ?? "http://localhost:5173" })); app.use(express.json({ limit: "20kb" }));
installMetrics(app);
app.get("/health", (_request, response) => response.json({ service: "location-service", status: "healthy" }));
app.use("/api/locations", locationRoutes); app.use("/api/admin/locations", adminRoutes); app.use("/api/internal/locations", internalRoutes); app.use(notFoundHandler); app.use(errorHandler);
export default app;
