apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: fixguard
  labels:
    app.kubernetes.io/name: location-service
    app.kubernetes.io/part-of: fixguard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: location-service
  ports:
    - name: http
      port: 4003
      targetPort: http
      protocol: TCP
