import { useEffect, useState } from "react";
import { locationApi } from "../api/client.js";

export default function AdminLocationsPage() {
  const [tab,setTab]=useState("districts"); const [data,setData]=useState({districts:[],areas:[],serviceZones:[]}); const [message,setMessage]=useState("");
  const [district,setDistrict]=useState({name:"",code:""}); const [area,setArea]=useState({districtId:"",name:"",postalCode:""}); const [zone,setZone]=useState({districtId:"",areaId:"",name:"",description:""});
  async function load(){try{const [d,a,z]=await Promise.all([locationApi("/api/admin/locations/districts"),locationApi("/api/admin/locations/areas"),locationApi("/api/admin/locations/service-zones")]);setData({districts:d.districts,areas:a.areas,serviceZones:z.serviceZones});}catch(e){setMessage(e.message);}}
  useEffect(()=>{load();},[]);
  async function create(path,payload,reset){setMessage("");try{await locationApi(`/api/admin/locations/${path}`,{method:"POST",body:JSON.stringify(payload)});reset();await load();setMessage("Location created.");}catch(e){setMessage(e.message);}}
  async function patch(path,id,payload){setMessage("");try{await locationApi(`/api/admin/locations/${path}/${id}`,{method:"PATCH",body:JSON.stringify(payload)});await load();setMessage("Location updated.");}catch(e){setMessage(e.message);}}
  function edit(path,item){const name=window.prompt("Name",item.name);if(name&&name!==item.name)patch(path,item.id,{name});}
  const activeDistricts=data.districts.filter((d)=>d.isActive); const zoneAreas=data.areas.filter((a)=>a.isActive&&String(a.districtId)===String(zone.districtId));
  return <section className="page"><div className="page-heading"><div><p className="eyebrow">Geographic structure</p><h1>Location Management</h1><p>Manage districts, areas, and future service responsibility zones.</p></div></div><div className="tabs">{["districts","areas","serviceZones"].map((value)=><button className={tab===value?"tab active":"tab"} onClick={()=>setTab(value)} key={value}>{value==="serviceZones"?"Service Zones":value[0].toUpperCase()+value.slice(1)}</button>)}</div>{message&&<p className="notice">{message}</p>}
  {tab==="districts"&&<><form className="panel inline-form" onSubmit={(e)=>{e.preventDefault();create("districts",district,()=>setDistrict({name:"",code:""}));}}><label>Name<input required value={district.name} onChange={(e)=>setDistrict({...district,name:e.target.value})}/></label><label>Code<input required value={district.code} onChange={(e)=>setDistrict({...district,code:e.target.value})}/></label><button className="primary-button">Add district</button></form><LocationTable items={data.districts} columns={["name","code"]} onEdit={(i)=>edit("districts",i)} onToggle={(i)=>patch("districts",i.id,{isActive:!i.isActive})}/></>}
  {tab==="areas"&&<><form className="panel inline-form" onSubmit={(e)=>{e.preventDefault();create("areas",{...area,districtId:Number(area.districtId),postalCode:area.postalCode||null},()=>setArea({districtId:"",name:"",postalCode:""}));}}><label>District<select required value={area.districtId} onChange={(e)=>setArea({...area,districtId:e.target.value})}><option value="">Select</option>{activeDistricts.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Name<input required value={area.name} onChange={(e)=>setArea({...area,name:e.target.value})}/></label><label>Postal code<input value={area.postalCode} onChange={(e)=>setArea({...area,postalCode:e.target.value})}/></label><button className="primary-button">Add area</button></form><LocationTable items={data.areas} columns={["name","postalCode"]} parent="district" onEdit={(i)=>edit("areas",i)} onToggle={(i)=>patch("areas",i.id,{isActive:!i.isActive})}/></>}
  {tab==="serviceZones"&&<><form className="panel inline-form" onSubmit={(e)=>{e.preventDefault();create("service-zones",{...zone,districtId:Number(zone.districtId),areaId:zone.areaId?Number(zone.areaId):null,description:zone.description||null},()=>setZone({districtId:"",areaId:"",name:"",description:""}));}}><label>District<select required value={zone.districtId} onChange={(e)=>setZone({...zone,districtId:e.target.value,areaId:""})}><option value="">Select</option>{activeDistricts.map((d)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Area (optional)<select value={zone.areaId} onChange={(e)=>setZone({...zone,areaId:e.target.value})}><option value="">District-wide</option>{zoneAreas.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Name<input required value={zone.name} onChange={(e)=>setZone({...zone,name:e.target.value})}/></label><label>Description<input value={zone.description} onChange={(e)=>setZone({...zone,description:e.target.value})}/></label><button className="primary-button">Add service zone</button></form><LocationTable items={data.serviceZones} columns={["name"]} parent="district" onEdit={(i)=>edit("service-zones",i)} onToggle={(i)=>patch("service-zones",i.id,{isActive:!i.isActive})}/></>}</section>;
}
function LocationTable({items,columns,parent,onEdit,onToggle}){return <section className="panel table-wrap"><table><thead><tr>{parent&&<th>District</th>}{columns.map((c)=><th key={c}>{c.replace(/([A-Z])/g," $1")}</th>)}<th>Status</th><th>Actions</th></tr></thead><tbody>{items.map((item)=><tr key={item.id}>{parent&&<td>{item[parent]?.name}</td>}{columns.map((c)=><td key={c}>{item[c]||"—"}</td>)}<td><span className={`badge ${item.isActive?"badge-verified":"badge-rejected"}`}>{item.isActive?"ACTIVE":"INACTIVE"}</span></td><td><div className="row-actions"><button className="secondary-button" onClick={()=>onEdit(item)}>Edit</button><button className="secondary-button" onClick={()=>onToggle(item)}>{item.isActive?"Deactivate":"Activate"}</button></div></td></tr>)}</tbody></table></section>}
