import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { locationApi, reportApi } from "../api/client.js";
const categories = ["POTHOLE", "STREETLIGHT", "WATER_LEAK", "GARBAGE", "DRAINAGE", "TRAFFIC_SIGNAL", "FALLEN_TREE", "ROAD_DAMAGE", "OTHER"];
export default function NewReportPage() {
  const navigate = useNavigate(); const [districts,setDistricts]=useState([]); const [areas,setAreas]=useState([]);
  const [form,setForm]=useState({title:"",category:"POTHOLE",description:"",districtId:"",areaId:"",address:"",latitude:"",longitude:""}); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  useEffect(()=>{locationApi("/api/locations/districts").then(({districts})=>setDistricts(districts)).catch(()=>setError("Locations are temporarily unavailable."));},[]);
  useEffect(()=>{setAreas([]); setForm((current)=>({...current,areaId:""})); if(form.districtId) locationApi(`/api/locations/districts/${form.districtId}/areas`).then(({areas})=>setAreas(areas)).catch((e)=>setError(e.message));},[form.districtId]);
  const change=(key)=>(event)=>setForm((current)=>({...current,[key]:event.target.value}));
  function locate(){navigator.geolocation?.getCurrentPosition(({coords})=>setForm((current)=>({...current,latitude:coords.latitude.toFixed(6),longitude:coords.longitude.toFixed(6)})),()=>setError("Location permission was not granted. Coordinates are optional."));}
  async function submit(event){event.preventDefault();setBusy(true);setError("");try{const payload={...form,districtId:Number(form.districtId),areaId:Number(form.areaId)};if(form.latitude&&form.longitude){payload.latitude=Number(form.latitude);payload.longitude=Number(form.longitude);}else{delete payload.latitude;delete payload.longitude;}const {report}=await reportApi("/api/reports",{method:"POST",body:JSON.stringify(payload)});navigate(`/citizen/reports/${report.id}`);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <section className="page narrow"><div className="page-heading"><div><p className="eyebrow">New report</p><h1>Tell the city what needs attention</h1><p>Choose a valid area, then describe the exact location.</p></div></div><form className="panel form-grid" onSubmit={submit}><label className="span-2">Issue title<input required value={form.title} onChange={change("title")}/></label><label>Category<select value={form.category} onChange={change("category")}>{categories.map((c)=><option key={c}>{c.replaceAll("_"," ")}</option>)}</select></label><label>District<select required value={form.districtId} onChange={change("districtId")}><option value="">Select district</option>{districts.map((d)=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Area<select required disabled={!form.districtId} value={form.areaId} onChange={change("areaId")}><option value="">Select area</option>{areas.map((a)=><option value={a.id} key={a.id}>{a.name}{a.postalCode?` (${a.postalCode})`:""}</option>)}</select></label><label>Specific address<input required value={form.address} onChange={change("address")}/></label><label className="span-2">Description<textarea required minLength="20" rows="5" value={form.description} onChange={change("description")}/></label><label>Latitude (optional)<input type="number" step="any" value={form.latitude} onChange={change("latitude")}/></label><label>Longitude (optional)<input type="number" step="any" value={form.longitude} onChange={change("longitude")}/></label><button type="button" className="secondary-button" onClick={locate}>Use my location</button>{error&&<p className="form-error span-2">{error}</p>}<button className="primary-button span-2" disabled={busy||!form.areaId}>{busy?"Submitting…":"Submit report"}</button></form></section>;
}
