apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: fixguard
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "4001"
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: fixguard
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
  ports:
    - name: http
      port: 4001
      targetPort: http
      protocol: TCP
